{
 "title": "Modem stats",
 "description": "VDSL modem monitoring dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Downstream speed (kbps)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXDOWN\"\n  )",
     "select": [
      [
       { "params": [ "MAXDOWN" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEDOWN\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream rate (kbps)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXUP\"\n  )",
     "select": [
      [
       { "params": [ "MAXUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEUP\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEUP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Synced speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXDOWN\"\n  )",
     "select": [
      [
       { "params": [ "MAXDOWN" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXUP\"\n  )",
     "select": [
      [
       { "params": [ "MAXUP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attainable speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEDOWN\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEDOWN" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEUP\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEUP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FEC errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"FECDOWN\"\n  )",
     "select": [
      [
       { "params": [ "FECUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"FECUP\"\n  )",
     "select": [
      [
       { "params": [ "FECDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CRC errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"CRCDOWN\"\n  )",
     "select": [
      [
       { "params": [ "CRCUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"CRCUP\"\n  )",
     "select": [
      [
       { "params": [ "CRCDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"POWERDOWN\"\n  )",
     "select": [
      [
       { "params": [ "POWERUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"POWERUP\"\n  )",
     "select": [
      [
       { "params": [ "POWERDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"SNRDOWN\"\n  )",
     "select": [
      [
       { "params": [ "SNRUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"SNRUP\"\n  )",
     "select": [
      [
       { "params": [ "SNRDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attenuation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTDOWN\"\n  )",
     "select": [
      [
       { "params": [ "ATTUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"modem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTUP\"\n  )",
     "select": [
      [
       { "params": [ "ATTDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FEC Errors in buckets last 24 hours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"modem\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FECDOWN\" or r[\"_field\"]==\"FECUP\")\n  //|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  //|> map(fn: (r)=>{return {r with _value: r.FECDOWN + r.FECUP}})\n  |> window(every: 2h)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n"
    }
   ]
  },
  {
   "title": "CRC Errors in buckets last 24 hours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"modem\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CRCDOWN\" or r[\"_field\"]==\"CRCUP\")\n  |> window(every: 2h)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n"
    }
   ]
  }
 ]
}