{
 "title": "Modem stats",
 "description": "VDSL line stats ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Bucket", "label": "Bucket", "query": "\tbuckets()" },
   { "name": "DataSource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "DSL Sync Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXDOWN\"\n  )",
     "select": [
      [
       { "params": [ "MAXDOWN" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEDOWN\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DSL Sync Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXUP\"\n  )",
     "select": [
      [
       { "params": [ "MAXUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEUP\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEUP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attainable Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"measurements\" and\r\n    r._field == \"ATTAINABLEDOWN\"\r\n  )"
    }
   ]
  },
  {
   "title": "Attainable Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"measurements\" and\r\n    r._field == \"ATTAINABLEUP\"\r\n  )"
    }
   ]
  },
  {
   "title": "SNR Downstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"measurements\" and\r\n    r._field == \"SNRDOWN\"\r\n  )"
    }
   ]
  },
  {
   "title": "SNR Upstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"measurements\" and\r\n    r._field == \"SNRUP\"\r\n  )"
    }
   ]
  },
  {
   "title": "Attenuation downstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"measurements\" and\r\n    r._field == \"ATTDOWN\"\r\n  )"
    }
   ]
  },
  {
   "title": "Attenuation upstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"measurements\" and\r\n    r._field == \"ATTUP\"\r\n  )"
    }
   ]
  },
  {
   "title": "Synced speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXDOWN\"\n  )",
     "select": [
      [
       { "params": [ "MAXDOWN" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"MAXUP\"\n  )",
     "select": [
      [
       { "params": [ "MAXUP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attainable speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEDOWN\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEDOWN" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTAINABLEUP\"\n  )",
     "select": [
      [
       { "params": [ "ATTAINABLEUP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"POWERDOWN\"\n  )",
     "select": [
      [
       { "params": [ "POWERUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"POWERUP\"\n  )",
     "select": [
      [
       { "params": [ "POWERDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attenuation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTDOWN\"\n  )",
     "select": [
      [
       { "params": [ "ATTUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"ATTUP\"\n  )",
     "select": [
      [
       { "params": [ "ATTDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"SNRDOWN\"\n  )",
     "select": [
      [
       { "params": [ "SNRUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"SNRUP\"\n  )",
     "select": [
      [
       { "params": [ "SNRDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FEC errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"FECDOWN\"\n  )",
     "select": [
      [
       { "params": [ "FECUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"FECUP\"\n  )",
     "select": [
      [
       { "params": [ "FECDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CRC errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"CRCDOWN\"\n  )",
     "select": [
      [
       { "params": [ "CRCUP" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurements",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"measurements\" and\n    r._field == \"CRCUP\"\n  )",
     "select": [
      [
       { "params": [ "CRCDOWN" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Forward Error Correction (FEC) Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FECDOWN\")\n  |> window(every: 1h)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n"
    }
   ]
  },
  {
   "title": "Forward Error Correction (FEC) Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FECUP\")\n  |> window(every: 1h)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n\n"
    }
   ]
  },
  {
   "title": "Cyclic redundancy check (CRC) Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CRCDOWN\")\n  |> window(every: 1h)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n\n"
    }
   ]
  },
  {
   "title": "Cyclic redundancy check (CRC) Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CRCUP\")\n  |> window(every: 1h)\n  |> spread()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> window(every: inf)\n\n"
    }
   ]
  }
 ]
}